controller_manager:
  ros__parameters:
    update_rate: 250  # Hz
    ar4_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    irb120_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: position_controllers/GripperActionController
    # dual_arms_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    irb120_gripper_controller:
      type: position_controllers/GripperActionController

ar4_trajectory_controller:
  ros__parameters:
    joints:
      - ar4_joint_1
      - ar4_joint_2
      - ar4_joint_3
      - ar4_joint_4
      - ar4_joint_5
      - ar4_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: true
    state_publish_rate: 250.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

irb120_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
    open_loop_control: true
    state_publish_rate: 250.0
    action_monitor_rate: 20.0
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

# dual_arms_controller:
#   ros__parameters:
#     joints:
#       # All joints of the AR4 arm
#       - ar4_joint_1
#       - ar4_joint_2
#       - ar4_joint_3
#       - ar4_joint_4
#       - ar4_joint_5
#       - ar4_joint_6
#       # All joints of the IRB120 arm
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#       - joint_5
#       - joint_6
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     open_loop_control: true
#     allow_partial_joints_goal: false
#     state_publish_rate: 250.0
#     action_monitor_rate: 20.0
#     constraints:
#       stopped_velocity_tolerance: 0.0
#       goal_time: 0.0

gripper_controller:
  ros__parameters:
    joint: ar4_gripper_jaw1_joint
    command_interface: position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
irb120_gripper_controller:
  ros__parameters:
    joint: left_joint
    command_interface: position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0

