# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    ar4_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    irb120_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # dual_arms_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

ar4_trajectory_controller:
  ros__parameters:
    joints:
      - ar4_joint_1
      - ar4_joint_2
      - ar4_joint_3
      - ar4_joint_4
      - ar4_joint_5
      - ar4_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
irb120_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
# dual_arms_controller:
#   ros__parameters:
#     joints:
#       - ar4_joint_1
#       - ar4_joint_2
#       - ar4_joint_3
#       - ar4_joint_4
#       - ar4_joint_5
#       - ar4_joint_6
#       - joint_1
#       - joint_2
#       - joint_3
#       - joint_4
#       - joint_5
#       - joint_6
# adham
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity
#     allow_nonzero_velocity_at_trajectory_end: true
gripper_controller:
  ros__parameters:
    joints:  # Change from 'joint' to 'joints'
      - ar4_gripper_jaw1_joint
      - ar4_gripper_jaw2_joint
